required = [
  "k8s.io/code-generator/cmd/client-gen",
  # needed by generated clientsets, but not an explicit dep in client-gen itself
  "k8s.io/apimachinery/pkg/apimachinery/registered",

  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
]

[[constraint]]
  name="k8s.io/client-go"
  version="v7.0.0"

[[constraint]]
  name="k8s.io/api"
  branch="release-1.10"

[[constraint]]
  name="k8s.io/apimachinery"
  branch="release-1.10"

[[constraint]]
  name="k8s.io/kubernetes"
  branch="release-1.10"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "github.com/dchest/blake2b"
  version = "1.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/DreamItGetIT/statuscake"
  source = "github.com/manifoldco/statuscake"

